version: "3.5"

services:
  wisestudy:
    container_name: wisestudy
    image: wisestudy:latest
    ports:
      - "80:80"
      - "22:22"
      - "3306:3306"
    sysctls:
      net.core.somaxconn: 1024
    networks:
      frontend:
        aliases:
          - local.wisestudy.com
    hostname: wisestudy-local
    volumes:
      - "../shell:/home/shell"
      #- "../python:/home/wisestudy"
    command:
      - /home/shell/init.sh

networks:
  frontend:
    driver: bridge
    name: frontend
    ipam:
      config:
      - subnet: 192.168.100.0/24
